allowBuilds:
  '@reown/appkit': false
  blake-hash: false
  bufferutil: false
  esbuild: false
  protobufjs: false
  secp256k1: false
  sharp: false
  tiny-secp256k1: false
  unrs-resolver: false
  usb: false
  utf-8-validate: false
